project_name: mc-server-runner
release:
  github:
    owner: craftignite
    name: mc-server-runner
brews:
  - install: |
      bin.install "mc-server-runner"
builds:
- goos:
  - linux
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  main: .
  env:
    - CGO_ENABLED=0
  binary: mc-server-runner
archives:
  - format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^misc:'
      - '^docs:'